<a href="https://colab.research.google.com/github/NicolLoaiza1/SIS-420-Lab-9/blob/main/Laboratorio_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [100]:
# Loaiza Alvarez Nicol Noelia
# Dataset Orosco Sardan Katerine productos de supermercado
# Este dataset no le veo muy optimo porque cambiar las letras a numeros es un trabajo muy costoso
# por lo que decidi hacer con 2 columnas que son puro numero que son mis x
# y una columna mi y que cambie las letras por numeros 
# Se pudo calcular las thetas con normalidad
# Pero las normal ya no pude me sale un error 
# En conclusion este dataset no es muy optimo puesto que no tiene muchas x o para tenerlas se requiere de modificar  

In [101]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [102]:
import os
import numpy as np
import pandas as pd
from matplotlib import pyplot
from mpl_toolkits.mplot3d import Axes3D 
%matplotlib inline

In [103]:
data = pd.read_csv("/content/drive/MyDrive/SIS 420 Dataset/productos-de-supermercados-sample.csv")
data = np.array(data)
x = data[:, 4:5]
y = data[:, 0]
m = y.size
print(x)
print('-'*45)
print(y)
print('-'*45)
print(m)

[[1.4]
 [10.75]
 [1.09]
 ...
 [5.99]
 [4.55]
 [4.99]]
---------------------------------------------
['mercadona-es' 'mercadona-es' 'mercadona-es' ... 'dia-es' 'mercadona-es'
 'dia-es']
---------------------------------------------
500000


In [104]:
def cambiarDatos(y):
  for i in range (m):
    if y[i] == "mercadona-es":
      y[i] = 1
    if y[i] == "carrefour-es":
      y[i] = 2
    if y[i] == "dia-es":
      y[i] = 3  

In [105]:
cambiarDatos(y)
print(y)

[1 1 1 ... 3 1 3]


In [129]:
def normalizarX(x):
  x_normalizada = []
  promedio = np.mean(x,axis=0)
  y = y.astype(float)
  desviacion_estandar = np.std(x,axis=0)
  for i in range(m):
    caracteristicas_x = []
    for j in range(x.shape[1]):
      if desviacion_estandar[j] != 0:
        caracteristicas_x.append((x[i,j]-promedio[j])/desviacion_estandar[j])
      else:
        caracteristicas_x.append(0)
    x_normalizada.append(caracteristicas_x)
  return x_normalizada, promedio, desviacion_estandar

In [107]:
x_normalizada, promedio, desviacion_estandar = normalizarX(x)
x_normalizada = np.array(x_normalizada)
x = np.concatenate((np.ones((m,1)),x_normalizada),axis=1)

print(x)
print('-'*45)
print(x_normalizada)

[[ 1.         -0.09021891]
 [ 1.          0.12908349]
 [ 1.         -0.0974899 ]
 ...
 [ 1.          0.01743863]
 [ 1.         -0.01633628]
 [ 1.         -0.00601617]]
---------------------------------------------
[[-0.09021891]
 [ 0.12908349]
 [-0.0974899 ]
 ...
 [ 0.01743863]
 [-0.01633628]
 [-0.00601617]]


In [108]:
def calcularCosto(x, y, theta):
  J = 0
  hipotesis = np.dot(x,theta)
  J = (1/(2*m))*np.sum(np.square((hipotesis)-y))
  return J

In [109]:
def computeCostMulti(X, y, theta):
    m = y.shape[0]  
    J = 0 
    h = np.dot(X, theta)  
    J = (1/(2 * m)) * np.sum(np.square(np.dot(X, theta) - y)) 
    return J

In [110]:
def descensoGradiente(x,y,theta,alpha,n_iteraciones):
  historial_J = []
  theta = theta.copy()
  for i in range(n_iteraciones):
    theta = theta-(alpha/m)*(np.dot(x,theta)-y).dot(x)
    historial_J.append(calcularCosto(x,y,theta))
  return theta, historial_J

In [111]:
def hallarTheta():
  theta = np.zeros(x.shape[1])
  n_iteraciones = 1000
  alpha = 0.003
  theta, historial_J = descensoGradiente(x,y,theta,alpha,n_iteraciones)
  return theta, historial_J

In [112]:
theta, historial_J = hallarTheta()
print("Las thetas encontradas son: ",theta)
print("El menor costo que se pudo determinar fue de: ",historial_J[-1])

Las thetas encontradas son:  [1.9128246281502743 -0.018177459898744756]
El menor costo que se pudo determinar fue de:  0.2104064751902816


In [116]:
data = pd.read_csv("/content/drive/MyDrive/SIS 420 Dataset/productos-de-supermercados-sample.csv", header=None)
data = np.array(data)
x = data[:, 4:5]
y = data[:, 0]
m = y.size
x = np.concatenate((np.ones((m,1)),x),axis=1)
print(x)
print(y)

[[1.0 'price']
 [1.0 '1.4']
 [1.0 '10.75']
 ...
 [1.0 5.99]
 [1.0 4.55]
 [1.0 4.99]]
['supermarket' 'mercadona-es' 'mercadona-es' ... 'dia-es' 'mercadona-es'
 'dia-es']


In [130]:
def metodoNormal(x, y):
  theta = np.dot(np.dot(np.linalg.inv(np.dot(x.T,x)),x.T),y)
  return theta